name: API-Security-Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '38 20 * * 3'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zap_scan:
    permissions:
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    name: Scan the API
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: openapi
          target: 'http://netbanking.apisec.ai:8080/v2/api-docs'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
